#! /bin/bash
## get the mingw-64 librarys, headers and tools
## two of these are redundant ... depending on your apt path
##  DONE apt-get install mingw-w64
##  DONE apt-get install mingw-w64-common
##  DONE apt-get install mingw-w64-tools
##  DONE apt-get install mingw-w64-x86-64-dev
##
## get the dependancies for the MXE cross build environment
##
    ##libtool-bin not found
## DONE apt-get install \
## DONE     autoconf automake autopoint bash bison bzip2 flex gettext\
## DONE     git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev \
## DONE     libltdl-dev libssl-dev libxml-parser-perl make \
## DONE     openssl p7zip-full patch perl pkg-config python ruby scons \
## DONE     sed unzip wget xz-utils
##
## download the MXE source tree
##
## NOT DONE cd ~
## NOT DONE git clone https://github.com/mxe/mxe.git
## ---->>> easier ,, download precompiled binaries
##
echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" > \
   /etc/apt/sources.list.d/mxeapt.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
sudo apt-get update
sudo apt-get install mxe-x86-64-w64-mingw32.static 
